version: '3.8'

services:
  frontend:
    image: urchytech/frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    image: urchytech/backend:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet: