version: "3.9"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"

    networks:
      - app-net

  backend:
    image: urchytech/backend:latest
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"

    networks:
      - app-net

  frontend:
    image: urchytech/frontend:latest
    ports:
      - "3000:80"
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
